/*
 * Copyright (c) 2013-2016 University of Maryland
 * Created by: Xi Yang 2014

 * Permission is hereby granted, free of charge, to any person obtaining a copy 
 * of this software and/or hardware specification (the “Work”) to deal in the 
 * Work without restriction, including without limitation the rights to use, 
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
 * the Work, and to permit persons to whom the Work is furnished to do so, 
 * subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Work.

 * THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS  
 * IN THE WORK.
 */
package net.maxgigapop.mrs.common;

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from
 * /Users/xyang/Work/RAINS/nml-mrs-model/source/rdf-model-examples/src/main/resources/mrs-spa.owl
 *
 * @author Auto-generated by schemagen on 09 Feb 2015 15:30
 */
public class Spa {

    /**
     * <
     * p>
     * The RDF model that holds the vocabulary terms</p>
     */
    private static Model m_model = ModelFactory.createDefaultModel();

    /**
     * <
     * p>
     * The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://schemas.ogf.org/mrs/2015/02/spa#";

    /**
     * <
     * p>
     * The namespace of the vocabulary as a string</p>
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    /**
     * <
     * p>
     * The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = m_model.createResource(NS);

    public static final Property dependOn = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#dependOn");

    public static final Property exportTo = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#exportTo");

    public static final Property importFrom = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#importFrom");

    public static final Property type = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#type");

    public static final Property value = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#value");

    public static final Property format = m_model.createProperty("http://schemas.ogf.org/mrs/2015/02/spa#format");

    public static final Resource Abstraction = m_model.createResource("http://schemas.ogf.org/mrs/2015/02/spa#Abstraction");

    public static final Resource Condition = m_model.createResource("http://schemas.ogf.org/mrs/2015/02/spa#Condition");

    public static final Resource PolicyAction = m_model.createResource("http://schemas.ogf.org/mrs/2015/02/spa#PolicyAction");

    public static final Resource PolicyData = m_model.createResource("http://schemas.ogf.org/mrs/2015/02/spa#PolicyData");

}
