"use strict";
define([],function(){
    /**These are the strings used in the model**/
    return{
        type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
        hasBidirectionalPort: "http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort",
        isAlias: "http://schemas.ogf.org/nml/2013/03/base#isAlias",
        namedIndividual: "http://www.w3.org/2002/07/owl#NamedIndividual",
        topology: "http://schemas.ogf.org/nml/2013/03/base#Topology",
        node: "http://schemas.ogf.org/nml/2013/03/base#Node",
        bidirectionalPort: "http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort",
        labelGroup: "http://schemas.ogf.org/nml/2013/03/base#LabelGroup",
        label: "http://schemas.ogf.org/nml/2013/03/base#Label",
        hasNode: "http://schemas.ogf.org/nml/2013/03/base#hasNode",
        hasService: "http://schemas.ogf.org/nml/2013/03/base#hasService",
        hasTopology: "http://schemas.ogf.org/nml/2013/03/base#hasTopology",
        networkAdress: "http://schemas.ogf.org/mrs/2013/12/topology#NetworkAddress",
        bucket: "http://schemas.ogf.org/mrs/2013/12/topology#Bucket",
        switchingSubnet: "http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet",
        hasNetworkAddress: "http://schemas.ogf.org/mrs/2013/12/topology#hasNetworkAddress",
        provideByService: "http://schemas.ogf.org/mrs/2013/12/topology#providedByService",
        hasBucket: "http://schemas.ogf.org/mrs/2013/12/topology#hasBucket",
        belongsTo: "http://schemas.ogf.org/nml/2013/03/base#belongsTo",
        name: "http://schemas.ogf.org/nml/2013/03/base#name",
        tag: "http://schemas.ogf.org/mrs/2013/12/topology#Tag",
        route: "http://schemas.ogf.org/mrs/2013/12/topology#Route",
        volume: "http://schemas.ogf.org/mrs/2013/12/topology#Volume",
        routingTable: "http://schemas.ogf.org/mrs/2013/12/topology#RoutingTable",
        hasVolume: "http://schemas.ogf.org/mrs/2013/12/topology#hasVolume",
        ontology: "http://www.w3.org/2002/07/owl#Ontology",
        POSIX_IOBenchmark: "http://schemas.ogf.org/mrs/2013/12/topology#POSIX_IOBenchmark",
        address: "http://schemas.ogf.org/mrs/2013/12/topology#Address",
        
        hypervisorService: "http://schemas.ogf.org/mrs/2013/12/topology#HypervisorService",
        routingService: "http://schemas.ogf.org/mrs/2013/12/topology#RoutingService",
        storageService: "http://schemas.ogf.org/mrs/2013/12/topology#StorageService",
        objectStorageService: "http://schemas.ogf.org/mrs/2013/12/topology#ObjectStorageService",
        blockStorageService: "http://schemas.ogf.org/mrs/2013/12/topology#BlockStorageService",
        IOPerformanceMeasurementService: "http://schemas.ogf.org/mrs/2013/12/topology#IOPerformanceMeasurementService",
        hypervisorBypassInterfaceService: "http://schemas.ogf.org/mrs/2013/12/topology#HypervisorBypassInterfaceService",
        virtualSwitchingService: "http://schemas.ogf.org/mrs/2013/12/topology#VirtualSwitchService",
        switchingService: "http://schemas.ogf.org/nml/2013/03/base#SwitchingService",
        topopolgySwitchingService: "http://schemas.ogf.org/mrs/2013/12/topology#SwitchingService",
        virtualCloudService: "http://schemas.ogf.org/mrs/2013/12/topology#VirtualCloudService"
    };
});