/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.maxgigapop.mrs.driver.aws;

import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Statement;
import com.hp.hpl.jena.rdf.model.StmtIterator;
import java.io.ByteArrayInputStream;
import java.io.StringWriter;
import net.maxgigapop.mrs.common.ModelUtil;
import net.maxgigapop.mrs.common.Mrs;
import net.maxgigapop.mrs.common.Nml;
import net.maxgigapop.mrs.common.RdfOwl;

/**
 *
 * @author max
 */
public class Test {

    /*public static void main(String[] args) throws Exception {
     String modelttl = "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n"
     + "@prefix owl:   <http://www.w3.org/2002/07/owl#> .\n"
     + "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n"
     + "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
     + "@prefix nml:   <http://schemas.ogf.org/nml/2013/03/base#> .\n"
     + "@prefix mrs:   <http://schemas.ogf.org/mrs/2013/12/topology#> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-123457>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"8\" ;\n"
     + "        mrs:target_device  \"/dev/xvda\" ;\n"
     + "        mrs:value          \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnet-85135bbf>\n"
     + "        a                      mrs:SwitchingSubnet , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-85135bbf> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:igwTag>\n"
     + "        a          mrs:Tag , owl:NamedIndividual ;\n"
     + "        mrs:type   \"gateway\" ;\n"
     + "        mrs:value  \"internet\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpc-c44f89a0>\n"
     + "        a                         nml:Topology , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-c44f89a0> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:igw-85c7ece0> ;\n"
     + "        nml:hasNode               <urn:ogf:network:aws.amazon.com:aws-cloud:i-4af55bea> ;\n"
     + "        nml:hasService            <urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-c44f89a0> , <urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-c44f89a0> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-ca0db8ae0.0.0.00>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"0.0.0.0/0\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.196.0.016>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec28110.196.0.016-subnet-a8a632f1> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec28110.196.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-66ce8042-cbef-45d2-9eb1-373edee1125d>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"12\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3>\n"
     + "        a            nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag   <urn:ogf:network:aws.amazon.com:aws-cloud:vpngwTag> ;\n"
     + "        nml:isAlias  <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgxadync> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281169.254.255.030>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec281169.254.255.030-subnet-a8a632f1> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec281169.254.255.030> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec281206.196.180.16027-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-a8a632f1\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-838451d8>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"8\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-8723d8mu75.40.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"75.40.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-twiki-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-f4fec3b6>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"8\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:igw-6cf01345>\n"
     + "        a           nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag  <urn:ogf:network:aws.amazon.com:aws-cloud:igwTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec2810.0.0.00>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"0.0.0.0/0\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpngwTag>\n"
     + "        a          mrs:Tag , owl:NamedIndividual ;\n"
     + "        mrs:type   \"gateway\" ;\n"
     + "        mrs:value  \"vpn\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-2cd6ad16>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/24\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-ca-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec28110.196.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"10.196.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu>\n"
     + "        a             mrs:RoutingTable , owl:NamedIndividual ;\n"
     + "        mrs:hasRoute  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu75.40.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu10.0.0.016> ;\n"
     + "        mrs:type      \"local\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2002>\n"
     + "        a          nml:LabelGroup , owl:NamedIndividual ;\n"
     + "        mrs:value  \"2002\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.1.0/24\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-e6a5a502-207b-4fc4-9ec1-8c7452e801b0>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.169> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch0>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-8504f54d> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch0> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.178>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.178\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec281169.254.255.030>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"169.254.255.0/30\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-94223f66-e92d-4fab-a591-a7759073f5b6>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.92> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.6>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.6\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu10.0.0.016-subnet-85135bbf>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-85135bbf\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.83>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.83\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnet-2cd6ad16>\n"
     + "        a                         mrs:SwitchingSubnet , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-2cd6ad16> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch1> , <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch0> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-123456> , <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch2> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-3ec68263>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.133> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnet-a8a632f1>\n"
     + "        a                         owl:NamedIndividual , mrs:SwitchingSubnet ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-a8a632f1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:eni-94223f66-e92d-4fab-a591-a7759073f5b6> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-766f8de7-9dc9-45a4-8e73-e2e456e35e2d> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-78334923> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-85c5492f-99dd-47d3-923d-ede3bd0fbf71> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-203d615e-b68b-4b82-a90b-0d3acc524a88> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-5fa0ad64-c979-43c6-8cd2-f227f2f21720> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-c7bed8dc-1f6d-40f5-a848-ceca4447b4bb> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-c2f961cb-55e4-4bbc-8682-3dee249ed41c> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-0dad73d4-549e-4ee7-aa1f-6d0bf28440f4> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-af34775e-6662-418a-b43c-364f5cf1e8ee> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-e6a5a502-207b-4fc4-9ec1-8c7452e801b0> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-60d281e1-a1ec-440d-b15f-9b7ee79b478d> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-71c6f2cb-9144-469d-9791-e234165670ed> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-3>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu75.40.0.016-subnet-85135bbf>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-85135bbf\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch1>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.166> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:portTag>\n"
     + "        a          mrs:Tag , owl:NamedIndividual ;\n"
     + "        mrs:type   \"interface\" ;\n"
     + "        mrs:value  \"network\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-45143020>\n"
     + "        a                         mrs:RoutingService , owl:NamedIndividual ;\n"
     + "        mrs:providesRoute         <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.196.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281206.196.180.16027> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281169.254.255.030> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec2810.0.0.00> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.0.0.016> ;\n"
     + "        mrs:providesRoutingTable  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu10.0.0.016>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    \"local\" ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu10.0.0.016-subnet-85135bbf> , <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu10.0.0.016-subnet-2cd6ad16> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-8723d8mu10.0.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec28110.196.0.016-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-a8a632f1\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.134>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.134\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.28>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.28\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-af34775e-6662-418a-b43c-364f5cf1e8ee>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.156> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-78334923>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.137> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-etc-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-c44f89a0>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-57ae4512>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"2\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-ca0db8ae10.0.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec28110.0.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae>\n"
     + "        a             mrs:RoutingTable , owl:NamedIndividual ;\n"
     + "        mrs:hasRoute  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae0.0.0.00> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae10.0.0.016> ;\n"
     + "        mrs:type      \"local\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-45143020>\n"
     + "        a                   mrs:SwitchingService , owl:NamedIndividual ;\n"
     + "        mrs:providesSubnet  <urn:ogf:network:aws.amazon.com:aws-cloud:subnet-a8a632f1> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.126>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.126\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae0.0.0.00>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:igw-85c7ece0> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-ca0db8ae0.0.0.00-subnet-6bb79632> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-ca0db8ae0.0.0.00> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-96aae36a>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-b1ff81f6> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:eni-78334923> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-c44f89a0>\n"
     + "        a                   mrs:SwitchingService , owl:NamedIndividual ;\n"
     + "        mrs:providesSubnet  <urn:ogf:network:aws.amazon.com:aws-cloud:subnet-6bb79632> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-a804f560>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"8\" ;\n"
     + "        mrs:target_device  \"/dev/xvda\" ;\n"
     + "        mrs:value          \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec2810.0.0.00-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-a8a632f1\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:igw-15891370>\n"
     + "        a           nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag  <urn:ogf:network:aws.amazon.com:aws-cloud:igwTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-2a1505d1>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"50\" ;\n"
     + "        mrs:target_device  \"/dev/sda1\" ;\n"
     + "        mrs:value          \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu10.0.0.016-subnet-2cd6ad16>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-2cd6ad16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgxadync>\n"
     + "        a                  nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag         <urn:ogf:network:aws.amazon.com:aws-cloud:virtualinterfaceTag> ;\n"
     + "        nml:hasLabel       <urn:ogf:network:aws.amazon.com:aws-cloud:vlan-1928> ;\n"
     + "        nml:hasLabelGroup  <urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup1928> ;\n"
     + "        nml:isAlias        <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-images-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgl0dgd1>\n"
     + "        a                  nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag         <urn:ogf:network:aws.amazon.com:aws-cloud:virtualinterfaceTag> ;\n"
     + "        nml:hasLabel       <urn:ogf:network:aws.amazon.com:aws-cloud:vlan-2003> ;\n"
     + "        nml:hasLabelGroup  <urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2003> ;\n"
     + "        nml:isAlias        <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-4235d62b> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-c80db8ac10.0.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu75.40.0.016-subnet-2cd6ad16>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-2cd6ad16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.81>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.81\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnet-6bb79632>\n"
     + "        a                         mrs:SwitchingSubnet , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-6bb79632> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:eni-3ec68263> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-3fc68262> , <urn:ogf:network:aws.amazon.com:aws-cloud:eni-39c68264> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.166>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.166\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec2810.0.0.00>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:igw-15891370> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec2810.0.0.00-subnet-a8a632f1> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec2810.0.0.00> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vlan-2003>\n"
     + "        a              nml:Label , owl:NamedIndividual ;\n"
     + "        mrs:value      \"2003\" ;\n"
     + "        nml:labeltype  <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae10.0.0.016>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    \"local\" ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-ca0db8ae10.0.0.016-subnet-6bb79632> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-ca0db8ae10.0.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.0.0.016>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    \"local\" ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec28110.0.0.016-subnet-a8a632f1> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec28110.0.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:igw-85c7ece0>\n"
     + "        a           nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag  <urn:ogf:network:aws.amazon.com:aws-cloud:igwTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-2f64394a10.0.0.016>\n"
     + "        a            mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop  \"local\" ;\n"
     + "        mrs:routeTo  <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-2f64394a10.0.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:s3service-us-east-1>\n"
     + "        a                   owl:NamedIndividual , mrs:ObjectStorageService ;\n"
     + "        mrs:providesBucket  <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-svn-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:elasticbeanstalk-us-east-1-873260731510> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-2> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-3> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-etc-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-images-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-twiki-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-ca-backup> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-c2f961cb-55e4-4bbc-8682-3dee249ed41c>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.97> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.132>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.132\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-c075d285>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"30\" ;\n"
     + "        mrs:value    \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-8c5f22e9>\n"
     + "        a                   mrs:SwitchingService , owl:NamedIndividual ;\n"
     + "        mrs:providesSubnet  <urn:ogf:network:aws.amazon.com:aws-cloud:subnet-2cd6ad16> , <urn:ogf:network:aws.amazon.com:aws-cloud:subnet-85135bbf> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vlan-1928>\n"
     + "        a              nml:Label , owl:NamedIndividual ;\n"
     + "        mrs:value      \"1928\" ;\n"
     + "        nml:labeltype  <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-9886da4d-26cf-4d21-855a-8d5f5ec19da3>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"12\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2003>\n"
     + "        a          nml:LabelGroup , owl:NamedIndividual ;\n"
     + "        mrs:value  \"2003\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.97>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.97\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-c80db8ac10.0.0.016>\n"
     + "        a            mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop  \"local\" ;\n"
     + "        mrs:routeTo  <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-c80db8ac10.0.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch1>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-miguelbatch2> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch1> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.137>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.137\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-b1ff81f6>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"8\" ;\n"
     + "        mrs:target_device  \"/dev/sda1\" ;\n"
     + "        mrs:value          \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281>\n"
     + "        a             mrs:RoutingTable , owl:NamedIndividual ;\n"
     + "        mrs:hasRoute  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.196.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281206.196.180.16027> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281169.254.255.030> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec2810.0.0.00> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec28110.0.0.016> ;\n"
     + "        mrs:type      \"main\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-e4fec281206.196.180.16027>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec281206.196.180.16027-subnet-a8a632f1> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec281206.196.180.16027> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-3fc68262>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.132> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup1928>\n"
     + "        a          nml:LabelGroup , owl:NamedIndividual ;\n"
     + "        mrs:value  \"1928\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpc-45143020>\n"
     + "        a                         nml:Topology , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-45143020> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> , <urn:ogf:network:aws.amazon.com:aws-cloud:igw-15891370> ;\n"
     + "        nml:hasNode               <urn:ogf:network:aws.amazon.com:aws-cloud:i-96aae36a> ;\n"
     + "        nml:hasService            <urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-45143020> , <urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-45143020> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-2f64394a>\n"
     + "        a             mrs:RoutingTable , owl:NamedIndividual ;\n"
     + "        mrs:hasRoute  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-2f64394a10.0.0.016> ;\n"
     + "        mrs:type      \"main\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.166>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.166\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.91>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.91\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:ebsservice-us-east-1>\n"
     + "        a                   owl:NamedIndividual , mrs:BlockStorageService ;\n"
     + "        mrs:providesVolume  <urn:ogf:network:aws.amazon.com:aws-cloud:vol-709f7fc5-6fc5-4a8d-971f-334ef6731568> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-2a1505d1> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-a804f560> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-66ce8042-cbef-45d2-9eb1-373edee1125d> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-f4fec3b6> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-838451d8> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-9886da4d-26cf-4d21-855a-8d5f5ec19da3> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-8504f54d> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-c075d285> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-98c5c051> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-123457> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-57ae4512> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-99c5c050> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-b1ff81f6> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-miguelbatch2> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-123456> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-7b4aed3e> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-4af55bea>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-2a1505d1> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:eni-3fc68262> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-123456>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.6> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-123456>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"30\" ;\n"
     + "        mrs:target_device  \"/dev/sda2\" ;\n"
     + "        mrs:value          \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch2>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.91> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.92>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.92\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.132>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.132\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-miguelbatch2>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"8\" ;\n"
     + "        mrs:target_device  \"/dev/xvda\" ;\n"
     + "        mrs:value          \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-svn-backup>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-709f7fc5-6fc5-4a8d-971f-334ef6731568>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"12\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-99c5c050>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"8\" ;\n"
     + "        mrs:value    \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-0dad73d4-549e-4ee7-aa1f-6d0bf28440f4>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.83> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-85c5492f-99dd-47d3-923d-ede3bd0fbf71>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.178> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-8723d8mu10.0.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-c44f89a0>\n"
     + "        a                         mrs:RoutingService , owl:NamedIndividual ;\n"
     + "        mrs:providesRoute         <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-c80db8ac10.0.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae0.0.0.00> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae10.0.0.016> ;\n"
     + "        mrs:providesRoutingTable  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-c80db8ac> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-ca0db8ae> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-ca0db8ae10.0.0.016-subnet-6bb79632>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-6bb79632\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpc-8c5f22e9>\n"
     + "        a                         nml:Topology , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress     <urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-8c5f22e9> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:igw-6cf01345> , <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-6cf01345> ;\n"
     + "        nml:hasNode               <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch2> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch1> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch0> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-123456> ;\n"
     + "        nml:hasService            <urn:ogf:network:aws.amazon.com:aws-cloud:switchingservice-vpc-8c5f22e9> , <urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-8c5f22e9> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-c7bed8dc-1f6d-40f5-a848-ceca4447b4bb>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.126> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-39c68264>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.134> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.169>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.169\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.198>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.198\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec28110.0.0.016-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-a8a632f1\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.156>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.1.156\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu75.40.0.016>\n"
     + "        a              mrs:Route , owl:NamedIndividual ;\n"
     + "        mrs:nextHop    <urn:ogf:network:aws.amazon.com:aws-cloud:igw-6cf01345> ;\n"
     + "        mrs:routeFrom  <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu75.40.0.016-subnet-85135bbf> , <urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-8723d8mu75.40.0.016-subnet-2cd6ad16> ;\n"
     + "        mrs:routeTo    <urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-8723d8mu75.40.0.016> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fggkfnmf>\n"
     + "        a                  nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag         <urn:ogf:network:aws.amazon.com:aws-cloud:virtualinterfaceTag> ;\n"
     + "        nml:hasLabelGroup  <urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2004> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-60d281e1-a1ec-440d-b15f-9b7ee79b478d>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.81> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-123456>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-123457> , <urn:ogf:network:aws.amazon.com:aws-cloud:vol-123456> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:eni-123456> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-ca0db8ae0.0.0.00-subnet-6bb79632>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-6bb79632\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:directconnect>\n"
     + "        a                         nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fggkfnmf> , <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgxadync> , <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgl0dgd1> , <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fh0jle37> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-203d615e-b68b-4b82-a90b-0d3acc524a88>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.28> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vgw-6cf01345>\n"
     + "        a           nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag  <urn:ogf:network:aws.amazon.com:aws-cloud:vpngwTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-766f8de7-9dc9-45a4-8e73-e2e456e35e2d>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.198> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-45143020>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.89>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.89\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-71c6f2cb-9144-469d-9791-e234165670ed>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.166> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routingservice-vpc-8c5f22e9>\n"
     + "        a                         mrs:RoutingService , owl:NamedIndividual ;\n"
     + "        mrs:providesRoute         <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-2f64394a10.0.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu75.40.0.016> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu10.0.0.016> ;\n"
     + "        mrs:providesRoutingTable  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-2f64394a> , <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-8723d8mu> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vgw-4235d62b>\n"
     + "        a            nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag   <urn:ogf:network:aws.amazon.com:aws-cloud:vpngwTag> ;\n"
     + "        nml:isAlias  <urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fgl0dgd1> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-2>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:routefrom-rtb-e4fec281169.254.255.030-subnet-a8a632f1>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"subnet\" ;\n"
     + "        mrs:value  \"subnet-a8a632f1\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch0>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.89> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:elasticbeanstalk-us-east-1-873260731510>\n"
     + "        a       mrs:Bucket , owl:NamedIndividual .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-98c5c051>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"10\" ;\n"
     + "        mrs:value    \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:10.0.0.133>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4:private\" ;\n"
     + "        mrs:value  \"10.0.0.133\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1>\n"
     + "        a               mrs:HypervisorService , owl:NamedIndividual ;\n"
     + "        mrs:providesVM  <urn:ogf:network:aws.amazon.com:aws-cloud:i-4af55bea> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-96aae36a> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch2> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-123456> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch0> , <urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch1> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2004>\n"
     + "        a          nml:LabelGroup , owl:NamedIndividual ;\n"
     + "        mrs:value  \"2004\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-6bb79632>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/24\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:i-miguelbatch2>\n"
     + "        a                         nml:Node , owl:NamedIndividual ;\n"
     + "        mrs:hasVolume             <urn:ogf:network:aws.amazon.com:aws-cloud:vol-a804f560> ;\n"
     + "        mrs:providedByService     <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:miguelenibatch2> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:virtualinterfaceTag>\n"
     + "        a          mrs:Tag , owl:NamedIndividual ;\n"
     + "        mrs:type   \"interface\" ;\n"
     + "        mrs:value  \"virtual\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:subnetnetworkaddress-subnet-85135bbf>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.1.0/24\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-e4fec281206.196.180.16027>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix-list\" ;\n"
     + "        mrs:value  \"206.196.180.160/27\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:dxvif-fh0jle37>\n"
     + "        a                  nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasTag         <urn:ogf:network:aws.amazon.com:aws-cloud:virtualinterfaceTag> ;\n"
     + "        nml:hasLabelGroup  <urn:ogf:network:aws.amazon.com:aws-cloud:labelGroup2002> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloudrouteto-rtb-2f64394a10.0.0.016>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:rtb-c80db8ac>\n"
     + "        a             mrs:RoutingTable , owl:NamedIndividual ;\n"
     + "        mrs:hasRoute  <urn:ogf:network:aws.amazon.com:aws-cloud:rtb-c80db8ac10.0.0.016> ;\n"
     + "        mrs:type      \"main\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-8504f54d>\n"
     + "        a                  mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb        \"8\" ;\n"
     + "        mrs:target_device  \"/dev/xvda\" ;\n"
     + "        mrs:value          \"standard\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud>\n"
     + "        a                         nml:Topology , owl:NamedIndividual ;\n"
     + "        mrs:hasBucket             <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-svn-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-twiki-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-ca-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-images-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-3> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-sdnx-etc-backup> , <urn:ogf:network:aws.amazon.com:aws-cloud:max-controller-full-backup-2> , <urn:ogf:network:aws.amazon.com:aws-cloud:elasticbeanstalk-us-east-1-873260731510> ;\n"
     + "        nml:hasBidirectionalPort  <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-6cf01345> , <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-4235d62b> , <urn:ogf:network:aws.amazon.com:aws-cloud:directconnect> , <urn:ogf:network:aws.amazon.com:aws-cloud:vgw-ba28cbd3> ;\n"
     + "        nml:hasService            <urn:ogf:network:aws.amazon.com:aws-cloud:ebsservice-us-east-1> , <urn:ogf:network:aws.amazon.com:aws-cloud:vpcservice-us-east-1> , <urn:ogf:network:aws.amazon.com:aws-cloud:ec2service-us-east-1> , <urn:ogf:network:aws.amazon.com:aws-cloud:s3service-us-east-1> ;\n"
     + "        nml:hasTopology           <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-45143020> , <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-c44f89a0> , <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-8c5f22e9> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:eni-5fa0ad64-c979-43c6-8cd2-f227f2f21720>\n"
     + "        a                      nml:BidirectionalPort , owl:NamedIndividual ;\n"
     + "        mrs:hasNetworkAddress  <urn:ogf:network:aws.amazon.com:aws-cloud:10.0.1.132> ;\n"
     + "        mrs:hasTag             <urn:ogf:network:aws.amazon.com:aws-cloud:portTag> .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vol-7b4aed3e>\n"
     + "        a            mrs:Volume , owl:NamedIndividual ;\n"
     + "        mrs:disk_gb  \"30\" ;\n"
     + "        mrs:value    \"gp2\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpcnetworkaddress-vpc-8c5f22e9>\n"
     + "        a          mrs:NetworkAddress , owl:NamedIndividual ;\n"
     + "        mrs:type   \"ipv4-prefix\" ;\n"
     + "        mrs:value  \"10.0.0.0/16\" .\n"
     + "\n"
     + "<urn:ogf:network:aws.amazon.com:aws-cloud:vpcservice-us-east-1>\n"
     + "        a                mrs:VirtualCloudService , owl:NamedIndividual ;\n"
     + "        mrs:providesVPC  <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-c44f89a0> , <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-45143020> , <urn:ogf:network:aws.amazon.com:aws-cloud:vpc-8c5f22e9> .";
        
     OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM_MICRO_RULE_INF);
     //$$ TODO: add ontology schema and namespace handling code
     try {
     model.read(new ByteArrayInputStream(modelttl.getBytes()), null, "TURTLE");
     } catch (Exception e) {
     throw new Exception(String.format("failure to unmarshall ontology model, due to %s", e.getMessage()));
     }
        
     BatchResourcesTool batch = new BatchResourcesTool();
     Model m = batch.addModelToBatch(model);
        
     StringWriter out = new StringWriter();
     try {
     m.write(out, "TURTLE");
     } catch (Exception e) {
     throw new Exception(String.format("failure to marshall ontology model, due to %s", e.getMessage()));
     }
     String ttl = out.toString();
        
     System.out.println(ttl);
     }*/
}
